version: '3.8'

services:
  app:
    container_name: app
    build: .
    working_dir: '/src'
    tty: true
    stdin_open: true
    volumes:
      - ./src:/src:cached
      - node_modules:/src/node_module
    ports:
      - '3000:3000'
      - '24678:24678' # 無限リロード対策
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
